version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./psql:/usr/src/db
    env_file: secure.env
    ports:
      - "15432:5432"
  redis:
    image: redis
    env_file: secure.env
    depends_on:
      - db
  web:
    build: .
    env_file: secure.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis